# 数据操作

首先，需要导入 `torch`：

In [1]:
import torch

## 入门

张量表示一个数值组成的数组，这个数组可能有多个维度：

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

访问张量的形状和张量中元素的总数：

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel()  # num of elements

12

改变一个张量的形状而不改变元素数量和元素值：

In [5]:
x = x.reshape(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

使用全0、全1、其他常量或者从特定分布中随机采样的数字：

In [6]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
torch.randn(3, 4)

tensor([[ 1.4131,  0.8662, -1.1007, -1.9137],
        [-0.8091,  0.4726,  0.3228,  1.0083],
        [ 0.2371, -0.7910, -1.1677, -0.5826]])

通过提供包含数值的 Python 列表（或嵌套列表）来为张量中的每个元素赋予确定值：

In [9]:
x = torch.tensor([[[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]])
x

tensor([[[2, 1, 4, 3],
         [1, 2, 3, 4],
         [4, 3, 2, 1]]])

In [10]:
x.shape

torch.Size([1, 3, 4])

In [11]:
x.numel()

12

## 运算符

常见的标准算术运算符：

In [12]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # ** 运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

按元素方式应用更多的计算：

In [13]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

把多个张量连结在一起：

In [14]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X, Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [15]:
torch.cat((X, Y), dim=0)  # 在第 0 维（行）合并

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [16]:
torch.cat((X, Y), dim=1)  # 在第 1 维（列）合并

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

通过逻辑运算符构建二元张量：

In [17]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [18]:
X > Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [19]:
X < Y

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

对张量中所有元素进行求和会产生一个只有一个元素的张量：

In [20]:
X.sum()

tensor(66.)

## 广播机制

即使形状不同，我们仍然可以通过调用广播机制（broadcasting mechanism）来执行按元素操作：

In [21]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [22]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [23]:
print(a.shape)
print(b.shape)
print((a + b).shape)

torch.Size([3, 1])
torch.Size([1, 2])
torch.Size([3, 2])


In [24]:
a = torch.arange(6).reshape((1, 2, 3))
b = torch.arange(4).reshape((2, 2, 1))
a, b

(tensor([[[0, 1, 2],
          [3, 4, 5]]]),
 tensor([[[0],
          [1]],
 
         [[2],
          [3]]]))

In [25]:
a + b

tensor([[[0, 1, 2],
         [4, 5, 6]],

        [[2, 3, 4],
         [6, 7, 8]]])

In [26]:
print(a.shape)
print(b.shape)
print((a + b).shape)

torch.Size([1, 2, 3])
torch.Size([2, 2, 1])
torch.Size([2, 2, 3])


## 索引和切片

In [27]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [28]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

通过指定索引来将元素写入矩阵：

In [29]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

为多个元素赋相同的值（按区域赋值）：

In [30]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 节省内存

运行一些操作可能会导致为新结果分配内存：

In [31]:
before = id(Y)
Y = Y + X
id(Y) == before

False

执行原地操作：

In [32]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 4903843312
id(Z): 4903843312


如果在后续计算中没有重复使用 `X`，我们也可以使用 `X[:] = X + Y` 或 `X += Y` 来减少操作的内存开销：

In [33]:
before = id(X)
X += Y
id(X) == before

True

## 转换成其他 Python 对象

转换成 Numpy 张量：

In [34]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

将大小为 1 的张量转换为 Python 标量：

In [35]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)