# 线性代数

## 1. 标量

标量由只有一个元素的张量表示：

In [1]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x ** y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

## 2. 向量

可以将向量视为标量组成的列表：

In [2]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

通过张量的索引来访问任一元素：

In [3]:
x[3]

tensor(3)


### 2.1 向量的长度、维度和形状
向量的长度：

In [4]:
len(x)

4

只有一个轴的张量，形状只有一个元素：

In [5]:
x.shape

torch.Size([4])

维度（dimension）这个词在不同上下文时往往会有不同的含义，这经常会使人感到困惑。为了清楚起见，我们在此明确一下：向量或轴的维度就被用来表示向量或轴的长度，即向量或轴的元素数量。然而张量的维度用来表示张量具有的轴数。在这个意义上，张量的某个轴的维度就是这个轴的长度。

## 3. 矩阵

通过指定两个分量 m 和 n 来创建一个形状为 m x n 的矩阵：

In [6]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

矩阵的转置：

In [7]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

对称矩阵（symmetric matrix）$B$ 等于其转置：$B = B^T $

In [12]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [13]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## 4. 张量

就像向量是标量的推广，矩阵是向量的推广一样，我们可以构建有更多轴的数据结构：

In [51]:
X = torch.arange(24).reshape(2, 3, 4)
X, len(X)

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 2)

## 5. 张量算法的基本性质

给定具有相同形状的任意两个张量，任何按元素二元计算的结果都将是相同形状的张量：

In [19]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

具体而言，两个矩阵按元素的乘法称为哈达玛积（Hadamard product），数学符号 $\odot$ 。

In [21]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

将张量乘以或者加上一个标量不会改变张量的形状，其中张量的每个元素都将与标量相乘或相加：

In [23]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
X, 
a + X, a * X

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]))

# 6. 降维
计算张量所有元素的和：

In [24]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

表示任意形状张量的元素和：

In [26]:
A, A.shape, A.sum()

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 torch.Size([5, 4]),
 tensor(190.))

指定张量沿哪一个轴来通过求和降低维度：

In [27]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [28]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [29]:
A.sum(axis=[0, 1])

tensor(190.)

一个与求和相关的量是平均值（mean 或 average）：

In [33]:
A.mean(), A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

In [34]:
A.mean(axis=0), A.sum(axis=0)/A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

## 6.1 非降维求和
计算总和或均值时保持轴数不变：

In [36]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

通过广播将 `A` 除以 `sum_A` ：

In [38]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

某个轴计算 `A` 元素的累积总和：

In [39]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

# 7. 点积
点积是相同位置按元素乘积的和：

In [40]:
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

我们可以通过执行按元素乘法，然后进行求和来表示两个向量的点积：

In [42]:
torch.sum(x * y)

tensor(6.)

# 8. 矩阵-向量积
矩阵向量积 $Ax$ 是一个长度为 $m$ 的列向量，其中第 $i$ 个元素是点积 $a_i^Tx$ ：

In [43]:
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

# 9. 矩阵-矩阵乘法
我们可以将矩阵-矩阵乘法 $AB$ 看作是简单地执行 $m$ 次矩阵-向量积，并将结果拼接在一起，形成一个 $n \times m$ 的矩阵：

In [46]:
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

# 10. 范数
$L_2$ 范数是向量元素平方和的平方根：

$$
\left\Vert X \right\Vert_2 = \sqrt{ \sum_{i=1}^n x_i^2 }
$$

In [48]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

$L_1$ 范数是向量元素的绝对值之和：

$$
\left\Vert X \right\Vert_1 = \sum_{i=1}^n \left\vert x_i \right\vert
$$

In [49]:
torch.abs(u).sum()弗luo bei ni wu si

tensor(7.)

矩阵的弗罗贝尼乌斯范数（Frobenius norm）是矩阵元素平方和的平方根：

$$
\left\Vert X \right\Vert_F = \sqrt{ \sum_{i=1}^m \sum_{j=1}^n x_{ij}^2 }
$$

In [50]:
torch.norm(torch.ones(4, 9))

tensor(6.)